### PR TITLE
Switch from inmemory cachetools-based cache to flask-caching disk cache

### LINKED ISSUE #13: Better caching
Looking at a debug build of tapalcatl-py, I see that 80-90% of the runtime is spent waiting around for S3 to do its job:

image

We already use [`cachetools`](https://github.com/tkem/cachetools) for an in-memory cache to reduce the time spent waiting for S3. @mojodna reminded me a while back that Lambda functions can store stuff to `/tmp` and it might still be there for the next execution. It might be a good idea to use a slightly more sophisticated caching system like [`flask-caching`](https://github.com/sh4nks/flask-caching) to store to `/tmp` so that we would get a better hit rate on those S3 objects.

This is also why we should build bigger metatiles 😄 .

### PR DESCRIPTION
**Pull request by iandees**
Fixes #13.

### CODE REVIEW

**Review by rmarianski — COMMENTED** [review]
Is there a memcache cache type too?

**Comment by iandees** [comment]
Yep! There's memcache and redis cache types: https://flask-caching.readthedocs.io/en/latest/#configuring-flask-caching

**Comment by iandees** [comment]
I haven't gone through the process of setting up a cache cluster yet because it would involve changing the Lambda config (running them on a VPC that is shared with the cache cluster).

**Comment by rmarianski** [comment]
👍 My intuition tells me that we'd get a better cache hit ratio using a cache that sits outside of the instance.

But you raise a good point about the vpc, and last time I looked it wasn't straightforward to have lambda on a vpc and also have it access the "internet", ie in this case s3 and memcache/redis. It involved having to set up a [nat gateway](https://aws.amazon.com/premiumsupport/knowledge-center/internet-access-lambda-function/) first.

**Pull request merged**
